pluginManagement {
    repositories {
        google()
        maven { url = uri('https://maven-central.storage-download.googleapis.com/maven2/') }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        // Primary Maven Central mirror avoids transient repo.maven.apache.org 403 responses.
        maven { url = uri('https://maven-central.storage-download.googleapis.com/maven2/') }
        mavenCentral()
    }
}

rootProject.name = 'TexiolDexkMobile'
include ':app'
